### ISSUE TITLE
BUG: invalid directory separator

### ISSUE THREAD

**Issue by ivanjaros** [go-swiss/fonts#1]
In `GetFontDetails` and `GetFontBytes`, the font is being loaded by this code:

`jsonFile, err := all.ReadFile(filepath.Join("all", normalizedFamilyName+".json"))`

The problem here is that the `all` is an `embed.FS` which has hardcoded forward slash as directory separator. But `filepath.Join` will use the `os.PathSeparator` which will be backward slash on windows and that will result in file not found error.

Due to this fact, this library does not work on Windows OS. The solution here is to simply use:
`jsonFile, err := all.ReadFile("all/" + normalizedFamilyName+".json")`

![obrázok](https://user-images.githubusercontent.com/64546059/208432046-a0664504-4351-4cb0-b686-2a790cf1a614.png)

Ref: https://github.com/stephenafamo/goldmark-pdf/issues/3

**Comment by stephenafamo** [comment]
Should be fixed in the latest version.
